<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="5" passed="4">
  <reporter-output>
  </reporter-output>
  <suite name="Command line suite" duration-ms="295974" started-at="2021-03-20T09:49:24Z" finished-at="2021-03-20T09:54:20Z">
    <groups>
    </groups>
    <test name="Command line test" duration-ms="295974" started-at="2021-03-20T09:49:24Z" finished-at="2021-03-20T09:54:20Z">
      <class name="ReactJsSanityTest.TC04_TodaysDealTest">
        <test-method status="FAIL" signature="loginUat()[pri:0, instance:ReactJsSanityTest.TC04_TodaysDealTest@48524010]" name="loginUat" duration-ms="117923" started-at="2021-03-20T11:52:22Z" finished-at="2021-03-20T11:54:20Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Price not updating Test Failed expected [R 499.00] but found [R 349.00]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Price not updating Test Failed expected [R 499.00] but found [R 349.00]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at ReactJsSanityTest.TC04_TodaysDealTest.loginUat(TC04_TodaysDealTest.java:198)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:77)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:159)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:106)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginUat -->
      </class> <!-- ReactJsSanityTest.TC04_TodaysDealTest -->
      <class name="ReactJsSanityTest.TC01_LoginTest">
        <test-method status="PASS" signature="loginUat()[pri:0, instance:ReactJsSanityTest.TC01_LoginTest@2aece37d]" name="loginUat" duration-ms="41270" started-at="2021-03-20T11:49:24Z" finished-at="2021-03-20T11:50:06Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginUat -->
      </class> <!-- ReactJsSanityTest.TC01_LoginTest -->
      <class name="ReactJsSanityTest.TC02_LogOutTest">
        <test-method status="PASS" signature="launchReactUat()[pri:0, instance:ReactJsSanityTest.TC02_LogOutTest@4b168fa9]" name="launchReactUat" duration-ms="45319" started-at="2021-03-20T11:50:06Z" finished-at="2021-03-20T11:50:51Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchReactUat -->
        <test-method status="PASS" signature="logOutUat()[pri:0, instance:ReactJsSanityTest.TC02_LogOutTest@4b168fa9]" name="logOutUat" duration-ms="31724" started-at="2021-03-20T11:50:51Z" finished-at="2021-03-20T11:51:23Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logOutUat -->
      </class> <!-- ReactJsSanityTest.TC02_LogOutTest -->
      <class name="ReactJsSanityTest.TC03_RegisterNewOnlineProfileTest">
        <test-method status="PASS" signature="loginUat()[pri:0, instance:ReactJsSanityTest.TC03_RegisterNewOnlineProfileTest@3ee0fea4]" name="loginUat" duration-ms="59624" started-at="2021-03-20T11:51:23Z" finished-at="2021-03-20T11:52:22Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginUat -->
      </class> <!-- ReactJsSanityTest.TC03_RegisterNewOnlineProfileTest -->
    </test> <!-- Command line test -->
  </suite> <!-- Command line suite -->
</testng-results>
